// screens/styles/HomeScreenStyles.js - CODE CORRECT ET PROPRE

import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5', // Fond clair
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 18,
    color: '#0D47A1',
  },
  headerGradient: {
    paddingTop: 50,
    paddingBottom: 25,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 8,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  menuButton: { // Style pour le bouton du menu sur HOMESCREEN
    paddingRight: 15,
    paddingVertical: 5,
  },
  headerGreeting: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    flex: 1,
    textAlign: 'center',
  },
  headerSettingsIcon: {
    marginLeft: 15,
  },
  headerSubtitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.8)',
    marginBottom: 20,
  },
  todayStatsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 15,
  },
  statBox: {
    alignItems: 'center',
  },
  statBoxValue: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  statBoxLabel: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.7)',
    marginTop: 2,
  },
  scrollViewContent: {
    paddingHorizontal: 15,
    paddingBottom: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#212121',
    marginBottom: 15,
    marginTop: 10,
    paddingLeft: 5,
  },
  filiereList: {
    paddingRight: 10,
    marginBottom: 30,
  },
  filiereCapsule: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 15,
    marginRight: 15,
    width: 200,
    height: 140,
    shadowColor: 'rgba(0,0,0,0.1)',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
    justifyContent: 'space-between',
  },
  capsuleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  capsuleName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#0D47A1',
  },
  capsuleRate: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FF5722',
  },
  capsuleModule: {
    fontSize: 13,
    color: '#555',
  },
  progressBarBackground: {
    height: 6,
    backgroundColor: '#E0E0E0',
    borderRadius: 3,
    marginTop: 10,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  capsuleProgressText: {
    fontSize: 12,
    color: '#777',
    marginTop: 5,
    textAlign: 'right',
  },
  missionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    marginBottom: 15,
    flexDirection: 'row',
    shadowColor: 'rgba(0,0,0,0.1)',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 8,
    overflow: 'hidden',
  },
  missionStatusIndicator: {
    width: 8,
  },
  missionContent: {
    flex: 1,
    padding: 15,
  },
  missionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  missionModule: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#212121',
    flex: 1,
    marginRight: 10,
  },
  missionStatus: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  missionStatusText: {
    fontSize: 13,
    fontWeight: 'bold',
    marginLeft: 5,
  },
  missionFiliere: {
    fontSize: 14,
    color: '#0D47A1',
    marginBottom: 10,
    fontWeight: '500',
  },
  missionInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  missionInfoIcon: {
    marginRight: 10,
    color: '#888',
  },
  missionInfoText: {
    fontSize: 13,
    color: '#555',
  },
  selectMissionButton: {
    backgroundColor: '#0D47A1',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 15,
    shadowColor: 'rgba(0,0,0,0.3)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 7,
  },
  selectMissionButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    marginRight: 5,
  },

  // Styles pour le menu latéral simulé (Modal) - Ceux-ci sont CORRECTS ici
  menuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'stretch', // S'étend sur toute la hauteur
  },
  menuContainer: {
    width: '75%',
    maxWidth: 300,
    backgroundColor: '#FFFFFF',
    height: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 15,
    borderRightWidth: 1,
    borderRightColor: 'rgba(0, 188, 212, 0.3)',
    borderTopRightRadius: 30,
    borderBottomRightRadius: 30,
    overflow: 'hidden',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  menuHeader: {
    paddingTop: 60,
    paddingBottom: 25,
    paddingHorizontal: 20,
    justifyContent: 'flex-end',
  },
  menuHeaderTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 5,
  },
  menuHeaderSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  menuItemsWrapper: {
    flex: 1,
    paddingTop: 20,
    paddingHorizontal: 20,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 15,
    borderRadius: 10,
    marginBottom: 8,
    backgroundColor: 'transparent',
    shadowColor: 'rgba(0,0,0,0.05)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  menuItemText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#212121',
  },
  menuIcon: {
    marginRight: 15,
  },
  menuSeparator: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(0, 188, 212, 0.3)',
    marginVertical: 18,
    marginHorizontal: 0,
  },
  logoutItem: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  logoutText: {
    color: '#D32F2F',
    fontWeight: 'bold',
  },
});

export default styles;